services:
  - type: web
    name: voice-access-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -t 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
